name: RCL

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  RCLtest:
    strategy:
      matrix:
        os: [windows-2019]
        node-version: [10.x]
        RCL: ["RCL1ToRCL2", "RCL2ToRCL3", "RCL3ToRCL4", "RCL4ToRCL5", "RCL5ToRCL6", "RCL6ToRCL7", "RCL7ToRCL8"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ matrix.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-${{ matrix.node-version }}-
            ${{ matrix.os }}-node-
            ${{ matrix.os }}-

      - run: npm install
      - run: npm run build
      - run: npx mocha test/integration/RCLTest/${{ matrix.RCL }}.RCLTest.ts

      - name: Update Code Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.RCL }}-dist
          path: dist

      - name: Update Server Artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.RCL }}-server
          path: server
